[project]
name = "open-api-to-mcp"
version = "0.1.0"
description = "OpenAPI to LLM-ready documentation converter with semantic search"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jsonref>=1.1.0",
]
